SET SERVEROUTPUT ON;
--CREATE A SEQUENCE FOR INCREMENTING USER ID
CREATE SEQUENCE USER_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
/
--DROP SEQUENCE USER_ID_SEQ;
--INSERTING IN Users TABLE
ACCEPT Name CHAR PROMPT'ENTER YOUR NAME: ';
DECLARE
    UID NUMBER;
    UName VARCHAR(50):= '&Name';
BEGIN
    SELECT USER_ID_SEQ.NEXTVAL INTO UID FROM DUAL;
    INSERT INTO Users VALUES(UID,UName);
    DBMS_OUTPUT.PUT_LINE('YOUR USER ID IS '||UID);
    COMMIT;
END;
/
